spring:
    application:
        name: api-gateway
        
# Tomcat Server Configuration
server:
    port: 7000
    
# Zuul Configuration Properties
zuul:
    routes:
        instance1:
            path: /api/instance-1/**
            serviceId: first-microservice
            
        instance2:
            path: /api/instance-2/**
            serviceId: second-microservice
   
# Eureka Configuration Properties
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
