spring:
    application:
        name: first-microservice
        
# Tomcat Server Configuration
server:
    port:
        8001
        
# Eureka Configuration Properties
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
