spring:
    application:
        name: server-microservice
        
# Tomcat Server Configuration
server:
    port: 8761
    
# Eureka Configuration Properties
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        
